### ISSUE TITLE
walkDir does not work

### ISSUE THREAD

**Issue by array-in-a-matrix** [HapticX/happyx#239]
**Describe the bug** 🐛

The `walkDir` iterator outputs nothing regardless of the contents of the directory.

**To Reproduce** 👨‍🔬
1. Create SPA
2. Use this code:
```nim
import happyx, os

appRoutes("app"):
  "/":
    tDiv:
      for i in walkDir("."): # does not work on all paths
        {i} # only an empty div is created regardless of how many files/directories exist
```
3. Run `hpx dev`

Output HTML:
```html
<html><head>
    <meta charset="utf8">
    <title>app</title>
    
  </head>
  <body>
    <div id="app"><div></div></div> <!-- only 1 empty div  created -->
    <script src="main.js"></script>
  <script>let socket = new WebSocket('ws://127.0.0.1:5000/hcr');
socket.onmessage = (event) => {
  if(event.data === 'true'){
    window.location.reload();
  }
};

function intervalSending(){
  socket.send('reload')
}

setInterval(intervalSending, 1000);
</script>
</body></html>
```

**Expected behavior** 🤔

The expected output should be like the following code:
```nim
import os
for i in walkDir("."):
  echo i # outputs current directory's contents
```
Using this code on https://play.nim-lang.org, outputs the following:
```nim
(kind: pcDir, path: "./nimble")
(kind: pcDir, path: "./nim")
```

**Please complete the following information** 📃
 - OS: [e.g. Win10] Arch Linux
 - OS Version [e.g. 22] Rolling
 - HappyX version [e.g. 2.4.1] (to see it you can use `hpx -v`) HappyX 3.8.0
 - HappyX project type [ssr/spa] SPA
 - Nim version [e.g. 2.0.0] 2.0.2
 - Browser [e.g. chrome] (For SPA projects) Firefox
 - Browser Version [e.g. 22] 121.0.1 (64-bit)

**Additional context** ✌

This may affect other iterators like `walkDirs` and `walkDirRec`. I did not check that though.

**Comment by quimt** [comment]
> The expected output should be like the following code:
> ```
> import os
> for i in walkDir("."):
>   echo i # outputs current directory's contents
> 
> ```

Well, that code doesn't work when placed outside the route either, in global scope. It only works if you put it in a `static: `block, in which case it is run as nimscript during the compilation process. The issue with most of the path procs from std/os is that they are not supported in browser js scripts, since the browser sandboxes code and hides access to the directory structure on the front end.

Since a SPA project is on the front-end, you either want to show the directory structure in which the project exists, which can only be gotten at compiletime, or you want your SPA script to be able to search around independently on a visitor's directory structure, which is a huge security no-no that browser sandboxing is meant to avoid. Or, you don't want to use a SPA at all and instead want to use an SSR to dynamically explore your own file structure.

**Comment by array-in-a-matrix** [comment]
Oh right, everything is being loaded client side so the file directory isn't available. Thank you for your explanation! I will probably switch to SSR or SSG then.
